# Generated by Django 5.1.2 on 2024-11-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0010_subscriptionprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionprice',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
