# Generated by Django 5.1.2 on 2024-11-11 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0012_subscriptionprice_featured_subscriptionprice_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionprice',
            old_name='Subscription',
            new_name='subscription',
        ),
    ]
