# Generated by Django 5.1.2 on 2024-12-02 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0024_usersubscription_cancel_at_period_end'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubscriptionManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
