# Generated by Django 5.1.2 on 2024-12-02 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0025_usersubscriptionmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSubscriptionManager',
        ),
    ]
