name: 2 - Django Basic

on:
  workflow_dispatch:
  push:
    branches: # Fixing the keyword
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4 # Specify the version explicitly
        with:
          python-version: '3.12'
      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
        working-directory: ./src
        run: |
          python manage.py test