name: 5 - Django Basic

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DJANGO_DEBUG: 0
      #DATABASE_URL: ${{secrets.NEON_DATABASE_URL}}
      NEON_API_KEY: ${{secrets.NEON_API_KEY}}
      NEON_PROJECT_ID: ${{secrets.NEON_PROJECT_ID}}
      NEON_PROD_BRANCH: "main"
      NEON_GITHUB_BRANCH: "gh-delete"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.11'
      - name: Install Neon CLI
        run: |
          npm install -g neonctl
      - name: Delete prev branch
        continue-on-error: true
        run: |
          neonctl branches delete "${{env.NEON_GITHUB_BRANCH}}" --project-id "${{env.NEON_PROJECT_ID}}"
      - name: Create new github actions branch
        run: |
          neonctl branches create --name"${{env.NEON_GITHUB_BRANCH}}" --parent --project-id "${{env.NEON_PROJECT_ID}}"
      - name: Database URL env val for new github actions branch
        run: |
          MY_NEON_C-ONN_STRING=$(neonctl connection-string --branch "${{env.NEON_GITHUB_BRANCH}}" --project-id "${{env.NEON_PROJECT_ID}}")
          echo "DJANGO_URL=$MY_NEON_CONN_STRING" >> $GITHUB_ENV
      - name: Setup Django Secret Key
        run: |
          MY_GEN_KEY=$(openssl rand -base64 32)
          echo 'DJANGO_SECRET_KEY=MY_GEN_KEY' >> $GITHUB_ENV
      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Django Migrate Database
        working-directory: ./src
        run: |
          python manage.py migrate
      - name: Django Tests
        working-directory: ./src
        run: |
          python manage.py test